### ISSUE TITLE
Need Help Understanding Autograder Feedback

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a03#1]
Can anyone explain what the autograder is trying to tell me? It seems rather vague.

<img width="640" alt="embargoed" src="https://user-images.githubusercontent.com/77807845/199845871-a65afd36-b461-4eab-915c-e7951dcfd810.PNG">

**Comment by jorbea** [comment]
I have the same response from the autograder. Not quite sure what to make of it.

**Comment by jpurvis2** [comment]
I also have the same response from the autograder. ^^^

**Comment by bdhack23** [comment]
Two more people are having this issue. Is something wrong with the autograder?

**Comment by nicwjh** [comment]
have the same issue.

**Comment by rmezapi** [comment]
I also have the same issue.

**Comment by vennila-t** [comment]
Several people are having the exact same issue. I and the other LAs will troubleshoot the autograder and give you all some feedback soon. Thank you for your patience.

**Comment by camsimba** [comment]
The test is meant to fail as of right now and you are meant to test it yourself, without feedback from an autograder. `"Tests are embargoed. Test your own code based on the instructions. This test will fail."` For right now just test your code personally and make sure it passes the expectations of the assignment, as it will be used for A04. This could be a good opportunity to delve into unit testing, try it out for yourself. Hope this helps!
