### ISSUE TITLE
Autograder: Tests still being embargoed

### ISSUE THREAD

**Issue by rcpang2024** [comp426-2022-fall/a03#10]
My autograder for a03 is still giving me the following error:
![image](https://user-images.githubusercontent.com/69740294/204706092-07766638-84c0-4b02-9943-5488fa329128.png)

I've tested my code in the terminal and it works fine, is there anything else I need to do? Because I've talked to some people and they said their autograders are passing.

**Comment by jdmar3** [comment]
I bumped an update to the autograder and it updated the autograder workflow in your repo, so this should work now. If it doesn't for some reason, just reopen this issue. It might take it a little while to update the last action run.
