### ISSUE TITLE
Copy of Assignment 3 and Original in Repository

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a03#2]
Not sure where else to post this question:
Something weird happened when I accepted Assignment 3. Originally it took a long time loading and loading before just saying there was an issue and that I needed to reaccept the assignment. So I reaccepted and it then went smoothly. But I noticed the version of assignment 3 that I have is titled "a03-bdhack23-1" while in the class repository, it has both "a03-bdhack23-1" and "a03-bdhack". However, I do not see "a03-bdhack23" in my own list of repositories. So its like only the class repository has both, and I'm just working on my copy. So I just wanted to let the professor and TAs know so they don't grade the wrong one, as I only have access to "a03-bdhack23-1", so that one is my actual assignment.

**Comment by vennila-t** [comment]
Sounds good, thanks for letting us know.

If you would like, we can rename your "a03-bdhack23-1" to "a03-bdhack23".

**Comment by bdhack23** [comment]
@vennila-t That would be nice! But make sure to not get it confused with the other one already called "a03-bdhack23"
