### ISSUE TITLE
Autograder: not telling what is wrong and the output matches the sample

### ISSUE THREAD

**Issue by teresa7218** [comp426-2022-fall/a03#4]
#### Which autograder check is failing?

Run Education/autograding@v1
![ff8fe2c4afb45eb1b416bec2b1c8940](https://user-images.githubusercontent.com/77808087/202088860-cd299f66-0dfa-44b7-8ff0-33fdac016196.png)

#### What is happening?
It says that my output does not match the test but I tested it on the terminal and it matches

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a03-teresa7218/actions/runs/3476619079

#### What should be happening?
it should pass the test

#### Screenshots of your local test(s)
![21155cf320dcf5001898a3a9cf3cd08](https://user-images.githubusercontent.com/77808087/202088964-420944ee-93b7-4949-b624-252eb1556932.png)
![46d334477d8c4e21fe049e1bbeacc52](https://user-images.githubusercontent.com/77808087/202090269-950511bd-c6b2-444b-bcee-28e575374e8d.png)

**Comment by vennila-t** [comment]
The autograder for a03 is not set up yet, so if your code is working as desired, you do not need to worry. I am unsure when it will be set up but in the meantime you can move to a04 if you are confident your a03 code works as intended
