### ISSUE TITLE
Autograder: Typo in Autograder

### ISSUE THREAD

**Issue by DheyaM** [comp426-2022-fall/a03#7]
I believe Line 19 in Autograder.json should be "comparison": "**regex**", instead of "comparison": "**included**" for the "Roll some dice" test

**Comment by jdmar3** [comment]
YUP! That's the thing. Or at least a thing. I just updated it. Let's give it a little while to chew on the repos now that I pushed an update and see what happens.

**Comment by DheyaM** [comment]
It works now. Thank you!

**Comment by jdmar3** [comment]
Aye good!
