### ISSUE TITLE
Autograder: Seemingly correct dice rolling is marked incorrect, unclear feedback

### ISSUE THREAD

**Issue by calebbg** [comp426-2022-fall/a03#8]
#### Which autograder check is failing?
Roll some dice

#### What is happening?
The autograder is failing despite my roll-dice code functioning as I believe it should. For further context, the same roll function works in a04 and those tests have passed.

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a03-calebbg/actions/runs/3574910375

#### What should be happening?
The expected output should match the actual output and the test should pass. 

#### Screenshots of your local test(s)
![a03dicerolls](https://user-images.githubusercontent.com/69723467/204559920-275208cb-f994-470e-8775-69f1aba1ba2b.JPG)
![a03autoerror](https://user-images.githubusercontent.com/69723467/204559917-c0d4aef6-dd73-4abe-800c-b8b5b399b547.JPG)

#### Why do you think the autograder is failing? 
I'm not entirely sure because the "expected" output is confusing to read, but I assume they are meant to be describing ranges of possible numbers. There could be a small typo with the numbers or formatting being checked for, or perhaps I am simply misinterpreting something.

**Comment by jdmar3** [comment]
It's  just a regex fail on my part. I'll fix whatever it is.

**Comment by DheyaM** [comment]
@jdmar3 @calebbg I think [this](https://github.com/comp426-2022-fall/a03/issues/7#issue-1468209025) issue addresses the specific change that needs to be made to the autograder

**Comment by calebbg** [comment]
@DheyaM Yeah that sounds right. Your issue wasn't up when I started writing this one, so in hindsight mine is redundant. Thanks for pointing that out
